apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
  namespace: dev
spec:
  kafka:
    version: 2.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    # storage:
    #   type: persistent-claim
    #   size: 1Gi
    #   class: longhorn
    #   deleteClaim: false
  zookeeper:
    replicas: 2
    storage:
      type: persistent-claim
      size: 1Gi
      class: longhorn
      deleteClaim: false
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"

    # kubectl apply -f kafka.yaml
