apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs_share
    server: 172.31.0.175
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  
