apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-zoo-01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-broker-01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi