
broker:
  replicaCount: 3
  persistence:
  #   enabled: true
  #   existingClaim: longhorn
  #   accessModes:
  #     - ReadWriteOnce
    size: 1Gi

controller:
  replicaCount: 0

kraft:
  enabled: false

zookeeper:
  enabled: true
  replicaCount: 3
  persistence:
  #   enabled: true
  #   existingClaim: longhorn
  #   accessModes:
  #     - ReadWriteOnce
   size: 1Gi

listeners:
  client:
    protocol: PLAINTEXT

  interbroker:
    protocol: PLAINTEXT

  external:
    protocol: PLAINTEXT

externalAccess:
  enabled: true
  broker:
    service:
      type: NodePort
      nodePorts:
        - 30066
        - 30067
        - 30068
      externalIPs:
        - 172.31.0.175
        - 172.31.0.175
        - 172.31.0.175
